### ISSUE TITLE
Issue when running the code.

### ISSUE THREAD

**Issue by subhashmandela** [BrainTech/matching-pursuit#1]
I installed the software following the steps mentioned by the contributer. When I run the code with an LFP signal, the software somehow changes the signal to something else (That is in the final output the signal shown is not the signal given) and decompose it using the matching pursuit. Please help me solve this issue.

**Comment by develancer** [comment]
Could you provide your configuration file and an input signal? Thanks.

**Comment by subhashmandela** [comment]
Hi,
Thank you very much for replying.
I cannot attach the LFP signal since it is provided by my research advisor. Sorry for that. But I am attaching a Gabor signal (gab.dat) which I generate using matlab. This also has the same issue when decomposed using the mp5 software. I am also attaching the configuration file (mp5_default.set) and the result of the mp decomposition (gab_smp.b).  All these files are enclosed in the mp_subhash.zip file.
[mp_subhash.zip](https://github.com/BrainTech/matching-pursuit/files/74758/mp_subhash.zip)

**Comment by subhashmandela** [comment]
Is it a problem with the way I use the software?

**Comment by develancer** [comment]
Yes, in a way. The mp5 binary needs an input signal (gab.dat) in a form of a binary file, not a text file. Each sample should be encoded as a 32-bit floating point value (float in C, float32 in python) in the endianness of the machine you're using (little endian on most computers). You can try [SVAROG](http://braintech.pl/svarog/) to read your signal and check its correctness.

You may also be interested in project [empi](https://github.com/develancer/empi), as it is a parallelized, faster version of MP5. You can use your current configuration file with empi, too. However, it is still an alpha version and some features may be missing (like multivariate MP decomposition).

**Comment by subhashmandela** [comment]
Thank you very much. The software works now !!!!

**Comment by develancer** [comment]
You're welcome.
